version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: harucard
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    container_name: db_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
